"""
Information about permission availability for different roles
"""

from . import permissions


ADMINISTRATOR_NAME = 'administrator'
ADMINISTRATOR_PERMISSIONS = {
    permissions.ADMIN_ACCESS: True,
    permissions.ADMIN_AUTHENTICATION_ACCESS: True,
    permissions.ADMIN_IMAGES_ACCESS: True,
    permissions.ADMIN_IMAGES_CREATE: True,
    permissions.ADMIN_IMAGES_DELETE: True,
    permissions.ADMIN_IMAGES_READ: True,
    permissions.ADMIN_IMAGES_UPDATE: True,
    permissions.ADMIN_COUNTRY_ACCESS: True,
    permissions.ADMIN_COUNTRY_CREATE: True,
    permissions.ADMIN_COUNTRY_DELETE: True,
    permissions.ADMIN_COUNTRY_READ: True,
    permissions.ADMIN_COUNTRY_UPDATE: True,
    permissions.ADMIN_CITY_ACCESS: True,
    permissions.ADMIN_CITY_CREATE: True,
    permissions.ADMIN_CITY_DELETE: True,
    permissions.ADMIN_CITY_READ: True,
    permissions.ADMIN_CITY_UPDATE: True,
    permissions.ADMIN_USER_LOGIN_ACCESS: True,
    permissions.ADMIN_USER_LOGIN_CREATE: True,
    permissions.ADMIN_USER_LOGIN_DELETE: True,
    permissions.ADMIN_USER_LOGIN_READ: True,
    permissions.ADMIN_USER_LOGIN_UPDATE: True,
    permissions.ADMIN_USER_INFO_ACCESS: True,
    permissions.ADMIN_USER_INFO_CREATE: True,
    permissions.ADMIN_USER_INFO_DELETE: True,
    permissions.ADMIN_USER_INFO_READ: True,
    permissions.ADMIN_USER_INFO_UPDATE: True,
    permissions.ADMIN_ROLE_ACCESS: True,
    permissions.ADMIN_ROLE_CREATE: True,
    permissions.ADMIN_ROLE_DELETE: True,
    permissions.ADMIN_ROLE_READ: True,
    permissions.ADMIN_ROLE_UPDATE: True,
    permissions.ADMIN_USER_ROLE_ACCESS: True,
    permissions.ADMIN_USER_ROLE_CREATE: True,
    permissions.ADMIN_USER_ROLE_READ: True,
    permissions.ADMIN_USER_ROLE_UPDATE: True,
    permissions.ADMIN_PUBLISHER_ACCESS: True,
    permissions.ADMIN_PUBLISHER_CREATE: True,
    permissions.ADMIN_PUBLISHER_DELETE: True,
    permissions.ADMIN_PUBLISHER_READ: True,
    permissions.ADMIN_PUBLISHER_UPDATE: True,
    permissions.ADMIN_GENRE_ACCESS: True,
    permissions.ADMIN_GENRE_CREATE: True,
    permissions.ADMIN_GENRE_DELETE: True,
    permissions.ADMIN_GENRE_READ: True,
    permissions.ADMIN_GENRE_UPDATE: True,
    permissions.ADMIN_GAME_ACCESS: True,
    permissions.ADMIN_GAME_CREATE: True,
    permissions.ADMIN_GAME_DELETE: True,
    permissions.ADMIN_GAME_READ: True,
    permissions.ADMIN_GAME_UPDATE: True,
    permissions.ADMIN_GAME_GENRE_ACCESS: True,
    permissions.ADMIN_GAME_GENRE_CREATE: True,
    permissions.ADMIN_GAME_GENRE_DELETE: True,
    permissions.ADMIN_GAME_GENRE_READ: True,
    permissions.ADMIN_GAME_GENRE_UPDATE: True,
    permissions.ADMIN_GAME_PURCHASE_ACCESS: True,
    permissions.ADMIN_GAME_PURCHASE_CREATE: True,
    permissions.ADMIN_GAME_PURCHASE_DELETE: True,
    permissions.ADMIN_GAME_PURCHASE_READ: True,
    permissions.ADMIN_GAME_PURCHASE_UPDATE: True,
    permissions.ADMIN_USER_LIBRARY_ACCESS: True,
    permissions.ADMIN_USER_LIBRARY_CREATE: True,
    permissions.ADMIN_USER_LIBRARY_DELETE: True,
    permissions.ADMIN_USER_LIBRARY_READ: True,
    permissions.ADMIN_USER_LIBRARY_UPDATE: True,
}

CONSULTANT_NAME = 'consultant'
CONSULTANT_PERMISSIONS = {
    permissions.BACKOFFICE_CHAT_MESSAGE_ATTACHMENT_CREATE: True,
    permissions.BACKOFFICE_CHAT_MESSAGE_CREATE: True,
    permissions.BACKOFFICE_CHAT_MESSAGE_DELETE: True,
    permissions.BACKOFFICE_CHAT_MESSAGE_DELETE_ACCESS: True,
    permissions.BACKOFFICE_CHAT_MESSAGE_DELETE_ALL: True,
    permissions.BACKOFFICE_CHAT_MESSAGE_HIDDEN_LIST: True,
    permissions.BACKOFFICE_CHAT_MESSAGE_LIST: True,
    permissions.BACKOFFICE_GLOBAL_PERMISSIONS_LIST: True,
    permissions.BACKOFFICE_GLOBAL_PERMISSIONS_READ: True,
    permissions.BACKOFFICE_LOGOUT: True,
    permissions.BACKOFFICE_PACKAGES_REQUEST_LIST: True,
    permissions.BACKOFFICE_PROFILE_READ: True,
    permissions.BACKOFFICE_SERVICE_REQUEST_AWAITING: True,
    permissions.BACKOFFICE_SERVICE_REQUEST_LIST: True,
    permissions.BACKOFFICE_SERVICE_REQUEST_READ: True,
    permissions.BACKOFFICE_SERVICE_REQUEST_SELF_ASSIGNEE: True,
    permissions.BACKOFFICE_SERVICE_REQUEST_STATUS_LIST: True,
    permissions.BACKOFFICE_ZADARMA_PHONE_WIDGET: True,
    permissions.LOGIN_WITH_PASSWORD: True,
}

CONTENT_MANAGER_NAME = 'content_manager'
CONTENT_MANAGER_PERMISSIONS = {
    permissions.ADMIN_ACCESS: True,
    permissions.ADMIN_CONTENT_ACCESS: True,
    permissions.ADMIN_CONTENT_BLOG_POST_CREATE: True,
    permissions.ADMIN_CONTENT_BLOG_POST_DELETE: True,
    permissions.ADMIN_CONTENT_BLOG_POST_LIST: True,
    permissions.ADMIN_CONTENT_BLOG_POST_READ: True,
    permissions.ADMIN_CONTENT_BLOG_POST_UPDATE: True,
    permissions.ADMIN_CONTENT_COMPANY_CONTACT_READ: True,
    permissions.ADMIN_CONTENT_COMPANY_CONTACT_UPDATE: True,
    permissions.ADMIN_CONTENT_COMPANY_DOCUMENT_CREATE: True,
    permissions.ADMIN_CONTENT_COMPANY_DOCUMENT_DELETE: True,
    permissions.ADMIN_CONTENT_COMPANY_DOCUMENT_READ: True,
    permissions.ADMIN_CONTENT_COMPANY_DOCUMENT_UPDATE: True,
    permissions.ADMIN_CONTENT_COMPANY_LIST: True,
    permissions.ADMIN_CONTENT_COMPANY_READ: True,
    permissions.ADMIN_CONTENT_COMPANY_SOCIAL_NETWORK_CREATE: True,
    permissions.ADMIN_CONTENT_COMPANY_SOCIAL_NETWORK_DELETE: True,
    permissions.ADMIN_CONTENT_COMPANY_SOCIAL_NETWORK_LIST: True,
    permissions.ADMIN_CONTENT_COMPANY_SOCIAL_NETWORK_READ: True,
    permissions.ADMIN_CONTENT_COMPANY_SOCIAL_NETWORK_UPDATE: True,
    permissions.ADMIN_CONTENT_COMPANY_UPDATE: True,
    permissions.ADMIN_CONTENT_INFORMATION_CATEGORY_CREATE: True,
    permissions.ADMIN_CONTENT_INFORMATION_CATEGORY_DELETE: True,
    permissions.ADMIN_CONTENT_INFORMATION_CATEGORY_LIST: True,
    permissions.ADMIN_CONTENT_INFORMATION_CATEGORY_READ: True,
    permissions.ADMIN_CONTENT_INFORMATION_CATEGORY_UPDATE: True,
    permissions.ADMIN_CONTENT_INFORMATION_PAGE_CREATE: True,
    permissions.ADMIN_CONTENT_INFORMATION_PAGE_DELETE: True,
    permissions.ADMIN_CONTENT_INFORMATION_PAGE_LIST: True,
    permissions.ADMIN_CONTENT_INFORMATION_PAGE_READ: True,
    permissions.ADMIN_CONTENT_INFORMATION_PAGE_UPDATE: True,
    permissions.ADMIN_CONTENT_REVIEW_CREATE: True,
    permissions.ADMIN_CONTENT_REVIEW_DELETE: True,
    permissions.ADMIN_CONTENT_REVIEW_LIST: True,
    permissions.ADMIN_CONTENT_REVIEW_READ: True,
    permissions.ADMIN_CONTENT_REVIEW_UPDATE: True,
    permissions.LOGIN_WITH_PASSWORD: True,
}
