"""
Information about permission mappings to roles
"""

from . import permissions


ADMIN_USER_ROLES_TO_ADD = {
    permissions.ADMIN_AUTHENTICATION_USERS_CREATE_ADMINISTRATOR: 'administrator',
    permissions.ADMIN_AUTHENTICATION_USERS_CREATE_CONSULTANT: 'consultant',
    permissions.ADMIN_AUTHENTICATION_USERS_CREATE_CONTENT_MANAGER: 'content_manager',
    permissions.ADMIN_AUTHENTICATION_USERS_CREATE_CUSTOMER: 'customer',
    permissions.ADMIN_AUTHENTICATION_USERS_CREATE_MANAGER: 'manager',
    permissions.ADMIN_AUTHENTICATION_USERS_CREATE_OFFLINE_MANAGER: 'offline_manager',
    permissions.ADMIN_AUTHENTICATION_USERS_CREATE_OFFLINE_MANAGER_PLUS: 'offline_manager_plus',
    permissions.ADMIN_AUTHENTICATION_USERS_CREATE_OPERATOR: 'operator',
    permissions.ADMIN_AUTHENTICATION_USERS_CREATE_PARTNER: 'partner',
    permissions.ADMIN_AUTHENTICATION_USERS_CREATE_SUPER_MANAGER: 'super_manager',
}

ADMIN_USER_ROLES_TO_LIST = {
    permissions.ADMIN_AUTHENTICATION_USERS_LIST_ADMINISTRATOR: 'administrator',
    permissions.ADMIN_AUTHENTICATION_USERS_LIST_CONSULTANT: 'consultant',
    permissions.ADMIN_AUTHENTICATION_USERS_LIST_CONTENT_MANAGER: 'content_manager',
    permissions.ADMIN_AUTHENTICATION_USERS_LIST_CUSTOMER: 'customer',
    permissions.ADMIN_AUTHENTICATION_USERS_LIST_MANAGER: 'manager',
    permissions.ADMIN_AUTHENTICATION_USERS_LIST_OFFLINE_MANAGER: 'offline_manager',
    permissions.ADMIN_AUTHENTICATION_USERS_LIST_OFFLINE_MANAGER_PLUS: 'offline_manager_plus',
    permissions.ADMIN_AUTHENTICATION_USERS_LIST_OPERATOR: 'operator',
    permissions.ADMIN_AUTHENTICATION_USERS_LIST_PARTNER: 'partner',
    permissions.ADMIN_AUTHENTICATION_USERS_LIST_SUPER_MANAGER: 'super_manager',
}

ADMIN_USER_ROLES_TO_READ = {
    permissions.ADMIN_AUTHENTICATION_USERS_READ_ADMINISTRATOR: 'administrator',
    permissions.ADMIN_AUTHENTICATION_USERS_READ_CONSULTANT: 'consultant',
    permissions.ADMIN_AUTHENTICATION_USERS_READ_CONTENT_MANAGER: 'content_manager',
    permissions.ADMIN_AUTHENTICATION_USERS_READ_CUSTOMER: 'customer',
    permissions.ADMIN_AUTHENTICATION_USERS_READ_MANAGER: 'manager',
    permissions.ADMIN_AUTHENTICATION_USERS_READ_OFFLINE_MANAGER: 'offline_manager',
    permissions.ADMIN_AUTHENTICATION_USERS_READ_OFFLINE_MANAGER_PLUS: 'offline_manager_plus',
    permissions.ADMIN_AUTHENTICATION_USERS_READ_OPERATOR: 'operator',
    permissions.ADMIN_AUTHENTICATION_USERS_READ_PARTNER: 'partner',
    permissions.ADMIN_AUTHENTICATION_USERS_READ_SUPER_MANAGER: 'super_manager',
}

ADMIN_USER_ROLES_TO_READ_PROFILE = {
    permissions.ADMIN_AUTHENTICATION_USERS_READ_ADMINISTRATOR_PROFILE: 'administrator',
    permissions.ADMIN_AUTHENTICATION_USERS_READ_CONSULTANT_PROFILE: 'consultant',
    permissions.ADMIN_AUTHENTICATION_USERS_READ_CONTENT_MANAGER_PROFILE: 'content_manager',
    permissions.ADMIN_AUTHENTICATION_USERS_READ_CUSTOMER_PROFILE: 'customer',
    permissions.ADMIN_AUTHENTICATION_USERS_READ_MANAGER_PROFILE: 'manager',
    permissions.ADMIN_AUTHENTICATION_USERS_READ_OFFLINE_MANAGER_PROFILE: 'offline_manager',
    permissions.ADMIN_AUTHENTICATION_USERS_READ_OFFLINE_MANAGER_PLUS_PROFILE: 'offline_manager_plus',
    permissions.ADMIN_AUTHENTICATION_USERS_READ_OPERATOR_PROFILE: 'operator',
    permissions.ADMIN_AUTHENTICATION_USERS_READ_PARTNER_PROFILE: 'partner',
    permissions.ADMIN_AUTHENTICATION_USERS_READ_SUPER_MANAGER_PROFILE: 'super_manager',
}

ADMIN_USER_ROLES_TO_SET = {
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_ROLE_TO_ADMINISTRATOR: 'administrator',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_ROLE_TO_CONSULTANT: 'consultant',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_ROLE_TO_CONTENT_MANAGER: 'content_manager',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_ROLE_TO_CUSTOMER: 'customer',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_ROLE_TO_MANAGER: 'manager',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_ROLE_TO_OFFLINE_MANAGER: 'offline_manager',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_ROLE_TO_OFFLINE_MANAGER_PLUS: 'offline_manager_plus',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_ROLE_TO_OPERATOR: 'operator',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_ROLE_TO_PARTNER: 'partner',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_ROLE_TO_SUPER_MANAGER: 'super_manager',
}

ADMIN_USER_ROLES_TO_UPDATE_ACTIVE = {
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_ADMINISTRATOR_ACTIVE: 'administrator',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_CONSULTANT_ACTIVE: 'consultant',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_CONTENT_MANAGER_ACTIVE: 'content_manager',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_CUSTOMER_ACTIVE: 'customer',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_MANAGER_ACTIVE: 'manager',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_OFFLINE_MANAGER_ACTIVE: 'offline_manager',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_OFFLINE_MANAGER_PLUS_ACTIVE: 'offline_manager_plus',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_OPERATOR_ACTIVE: 'operator',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_PARTNER_ACTIVE: 'partner',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_SUPER_MANAGER_ACTIVE: 'super_manager',
}

ADMIN_USER_ROLES_TO_UPDATE_EMAIL = {
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_ADMINISTRATOR_EMAIL: 'administrator',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_CONSULTANT_EMAIL: 'consultant',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_CONTENT_MANAGER_EMAIL: 'content_manager',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_CUSTOMER_EMAIL: 'customer',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_MANAGER_EMAIL: 'manager',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_OFFLINE_MANAGER_EMAIL: 'offline_manager',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_OFFLINE_MANAGER_PLUS_EMAIL: 'offline_manager_plus',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_OPERATOR_EMAIL: 'operator',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_PARTNER_EMAIL: 'partner',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_SUPER_MANAGER_EMAIL: 'super_manager',
}

ADMIN_USER_ROLES_TO_UPDATE_PASSWORD = {
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_ADMINISTRATOR_PASSWORD: 'administrator',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_CONSULTANT_PASSWORD: 'consultant',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_CONTENT_MANAGER_PASSWORD: 'content_manager',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_CUSTOMER_PASSWORD: 'customer',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_MANAGER_PASSWORD: 'manager',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_OFFLINE_MANAGER_PASSWORD: 'offline_manager',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_OFFLINE_MANAGER_PLUS_PASSWORD: 'offline_manager_plus',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_OPERATOR_PASSWORD: 'operator',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_PARTNER_PASSWORD: 'partner',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_SUPER_MANAGER_PASSWORD: 'super_manager',
}

ADMIN_USER_ROLES_TO_UPDATE_PHONE = {
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_ADMINISTRATOR_PHONE: 'administrator',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_CONSULTANT_PHONE: 'consultant',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_CONTENT_MANAGER_PHONE: 'content_manager',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_CUSTOMER_PHONE: 'customer',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_MANAGER_PHONE: 'manager',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_OFFLINE_MANAGER_PHONE: 'offline_manager',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_OFFLINE_MANAGER_PLUS_PHONE: 'offline_manager_plus',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_OPERATOR_PHONE: 'operator',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_PARTNER_PHONE: 'partner',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_SUPER_MANAGER_PHONE: 'super_manager',
}

ADMIN_USER_ROLES_TO_UPDATE_PROFILE = {
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_ADMINISTRATOR_PROFILE: 'administrator',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_CONSULTANT_PROFILE: 'consultant',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_CONTENT_MANAGER_PROFILE: 'content_manager',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_CUSTOMER_PROFILE: 'customer',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_MANAGER_PROFILE: 'manager',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_OFFLINE_MANAGER_PROFILE: 'offline_manager',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_OFFLINE_MANAGER_PLUS_PROFILE: 'offline_manager_plus',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_OPERATOR_PROFILE: 'operator',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_PARTNER_PROFILE: 'partner',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_SUPER_MANAGER_PROFILE: 'super_manager',
}

ADMIN_USER_ROLES_TO_UPDATE_ROLE = {
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_ADMINISTRATOR_ROLE: 'administrator',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_CONSULTANT_ROLE: 'consultant',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_CONTENT_MANAGER_ROLE: 'content_manager',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_CUSTOMER_ROLE: 'customer',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_MANAGER_ROLE: 'manager',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_OFFLINE_MANAGER_ROLE: 'offline_manager',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_OFFLINE_MANAGER_PLUS_ROLE: 'offline_manager_plus',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_OPERATOR_ROLE: 'operator',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_PARTNER_ROLE: 'partner',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_SUPER_MANAGER_ROLE: 'super_manager',
}

ADMIN_USER_ROLES_TO_UPDATE_USERNAME = {
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_ADMINISTRATOR_USERNAME: 'administrator',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_CONSULTANT_USERNAME: 'consultant',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_CONTENT_MANAGER_USERNAME: 'content_manager',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_CUSTOMER_USERNAME: 'customer',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_MANAGER_USERNAME: 'manager',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_OFFLINE_MANAGER_USERNAME: 'offline_manager',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_OFFLINE_MANAGER_PLUS_USERNAME: 'offline_manager_plus',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_OPERATOR_USERNAME: 'operator',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_PARTNER_USERNAME: 'partner',
    permissions.ADMIN_AUTHENTICATION_USERS_UPDATE_SUPER_MANAGER_USERNAME: 'super_manager',
}
