"""
Collection of available permissions
"""

ADMIN_ACCESS = 'admin_access'
ADMIN_AUTHENTICATION_ACCESS = 'admin_authentication_access'
ADMIN_AUTHENTICATION_PARTNER_CERTIFICATE_ACCESS = 'admin_authentication_partner_certificate_access'
ADMIN_AUTHENTICATION_PARTNER_CERTIFICATE_CERT_CODE_CREATE = 'admin_authentication_partner_certificate_cert_code_create'
ADMIN_AUTHENTICATION_PARTNER_CERTIFICATE_CERT_CODE_DELETE = 'admin_authentication_partner_certificate_cert_code_delete'
ADMIN_AUTHENTICATION_PARTNER_CERTIFICATE_CERT_CODE_LIST = 'admin_authentication_partner_certificate_cert_code_list'
ADMIN_AUTHENTICATION_PARTNER_CERTIFICATE_CERT_CODE_READ = 'admin_authentication_partner_certificate_cert_code_read'
ADMIN_AUTHENTICATION_PARTNER_CERTIFICATE_CERT_CODE_UPDATE = 'admin_authentication_partner_certificate_cert_code_update'
