DROP DATABASE IF EXISTS mobile_shop;

CREATE DATABASE mobile_shop;

CREATE TABLE IF NOT EXISTS images
(
    id SERIAL PRIMARY KEY NOT NULL UNIQUE,
    image bytea DEFAULT bytea_import('/Users/macbook/Desktop/MobileShop/scripts/default_image.png')
);

CREATE TABLE IF NOT EXISTS country
(
  id SERIAL PRIMARY KEY NOT NULL UNIQUE,
  name VARCHAR(128) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS city
(
  id SERIAL PRIMARY KEY NOT NULL UNIQUE,
  name VARCHAR(128) NOT NULL UNIQUE,
  country_id INTEGER REFERENCES country(id) ON DELETE CASCADE NOT NULL
);

CREATE TABLE IF NOT EXISTS user_login
(
    id SERIAL PRIMARY KEY NOT NULL,
    username VARCHAR(128) NOT NULL UNIQUE,
    password VARCHAR(256) NOT NULL
);

CREATE TABLE IF NOT EXISTS user_info
(
    id SERIAL PRIMARY KEY NOT NULL UNIQUE,
    user_id INTEGER REFERENCES user_login(id) ON DELETE CASCADE NOT NULL UNIQUE,
    first_name VARCHAR(128) NOT NULL,
    last_name VARCHAR(128) NULL,
    location_id INTEGER REFERENCES city(id) ON DELETE CASCADE NOT NULL,
    image_id INTEGER REFERENCES images(id) ON DELETE CASCADE NOT NULL
);

-- Admin, Publisher, User
CREATE TABLE IF NOT EXISTS role
(
    id SERIAL PRIMARY KEY NOT NULL UNIQUE,
    name VARCHAR(128) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS user_role
(
    id SERIAL PRIMARY KEY NOT NULL UNIQUE,
    person_id INTEGER REFERENCES user_login(id) ON DELETE CASCADE NOT NULL UNIQUE,
    role_id INTEGER REFERENCES role(id) ON DELETE RESTRICT NOT NULL
);

CREATE TABLE IF NOT EXISTS publisher
(
    id SERIAL PRIMARY KEY NOT NULL UNIQUE,
    name VARCHAR(128) NOT NULL UNIQUE,
    country_id INTEGER REFERENCES country(id) ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS game
(
    id SERIAL PRIMARY KEY NOT NULL UNIQUE,
    name VARCHAR(128) NOT NULL UNIQUE,
    description VARCHAR(2048) NOT NULL,
    price MONEY NOT NULL,
    publisher_id INTEGER REFERENCES publisher(id) ON DELETE CASCADE NOT NULL,
    dt_release TIMESTAMP NOT NULL,
    image_id INTEGER REFERENCES images(id) ON DELETE CASCADE NOT NULL
);

CREATE TABLE IF NOT EXISTS game_purchase
(
    id SERIAL PRIMARY KEY NOT NULL UNIQUE,
    game_id INTEGER REFERENCES game(id) ON DELETE NO ACTION NOT NULL,
    dt_created TIMESTAMP NOT NULL,
    timestamp TIMESTAMP NULL
);

CREATE TABLE IF NOT EXISTS user_library
(
    id SERIAL PRIMARY KEY NOT NULL UNIQUE,
    user_id INTEGER REFERENCES user_login(id) ON DELETE CASCADE NOT NULL,
    game_id INTEGER REFERENCES game(id) ON DELETE CASCADE NOT NULL
);

CREATE EXTENSION pgcrypto;


